export const ADD_INGREDIENTS = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENT';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENT_FAILED';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';