export const ADD_INGREDIENTS = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENT';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENT_FAILED';